Adds arm64 to rock images (#36)
* Adds arm64 to rock images

Previously, we've skipped adding support for arm64 since some of the
rocks failed to build for arm64.

* Fixes longhorn-manager arm64 rocks

The ``iputils`` snap does nto have an arm64 target, so we can't use that
for arm64.

The iputils rpm  from suse (installed in the original Dockerfile) contains the
following binaries: arping, clockdiff, ping, tracepath.
It also contains symlinks for ping6 and tracepath6.

We'll be installing equivalent apt packages for those binaries to keep
parity.

* Fixes v1.7.0 longhorn-engine and longhorn-instance-manager arm64 rocks

When building tgt, we're getting this error on arm64:

```
bs.c: In function ‘bs_sig_request_done’:
bs.c:196:15: error: ‘read’ writing 1 byte into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
  196 |         ret = read(fd, (char *)siginfo, sizeof(siginfo));
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bs.c:193:33: note: destination object ‘siginfo’ of size 0
  193 |         struct signalfd_siginfo siginfo[16];
      |                                 ^~~~~~~
In file included from /usr/include/unistd.h:1217,
                 from bs.c:33:
/usr/include/aarch64-linux-gnu/bits/unistd.h:26:1: note: in a call to function ‘read’ declared with attribute ‘access (write_only, 2)’
   26 | read (int __fd, void *__buf, size_t __nbytes)
      | ^~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:95: bs.o] Error 1
make[1]: Leaving directory '/root/parts/build-tgt/build/usr'
make: *** [Makefile:24: programs] Error 2
'override-build' in part 'build-tgt' failed with code 2.
```

After some investigation, it seems that this Warning is not a false positive.
Because ``# if defined(__NR_signalfd)`` is false, ``signalfd_siginfo`` is an empty structure,
which means that siginfo is actually an array of elements that have 0 bytes in size.
It seems that on arm64, there's only ``__NR_signalfd4``, not ``__NR_signalfd``.

Interestingly, this does not occur on ubuntu 22.04, which is why we're
not seeing this issue in the v1.6.2 rocks.

xref: https://www.spinics.net/lists/linux-stgt/msg04783.html

This patch is a cherry-pick of the following commit (+ resolved conflicts), which solves this issue:

https://github.com/fujita/tgt/commit/7ea559753e647e6a5fa5a0ca3c29ba417d9744b7